plugins {
	id 'java-library'
	id 'application'
	id 'maven-publish'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
	id 'org.openjfx.javafxplugin' version '0.1.0'
	id 'org.gradlex.extra-java-module-info' version '1.8'
}

repositories {
	mavenCentral()
	maven {
		name "Fabric"
		url 'https://maven.fabricmc.net/'
	}
	maven {
		name "Quilt"
		url 'https://maven.quiltmc.org/repository/release/'
	}
}

archivesBaseName = 'matcher'
group = 'org.quiltmc'

sourceSets {
	main {
		java
		resources
	}
}

javafx {
	version = "21"
	modules = [ 'javafx.controls', 'javafx.web' ]
}

java {
	modularity.inferModulePath = true
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21

	if (!JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_21)) {
		toolchain {
			languageVersion = JavaLanguageVersion.of(21)
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 21
}

dependencies {
    implementation "com.github.javaparser:javaparser-core:3.8.3"
	implementation "org.quiltmc:procyon-quilt-compilertools:0.5.35.local"
	api "org.ow2.asm:asm:9.7"
	implementation "org.ow2.asm:asm-commons:9.7"
	api "org.ow2.asm:asm-tree:9.7"
	implementation "org.ow2.asm:asm-util:9.7"
	implementation "net.fabricmc:mapping-io:0.6.1"
	implementation "org.quiltmc:cfr:0.0.6"
	implementation "org.vineflower:vineflower:1.11.1"
}

extraJavaModuleInfo {
	automaticModule("cfr-0.0.6.jar", "cfr")
	automaticModule("procyon-quilt-compilertools-0.5.35.local.jar", "procyon.compilertools")
	automaticModule("procyon-quilt-core-0.5.35.local.jar", "procyon.core")
	automaticModule("vineflower-1.11.1.jar", "intellij.fernflower")
}

application {
	mainModule = 'matcher'
	mainClass = 'matcher.Main'
}

build.dependsOn(shadowJar)

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}
